[project]
name = "gsheets2api"
version = "0.1.0"
description = "Examples for consuming GSX2JSON/OpenSheet API"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.2.0",
    "pandas>=3.0.0",
    "requests>=2.32.5",
]
